# Symfony/app/config/security.yml

# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    #-- Méthode d'encodage des MDP
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        OC\UserBundle\Entity\User: plaintext

    #-- Différents role
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username
            #entity:
            #    class:    OC\UserBundle\Entity\User
            #    property: username
        #in_memory:
        #    memory:
        #        users:
        #            user:  {password: userpass, roles:['ROLE_USER']}
        #            auteur:  {password: auteur, roles:['ROLE_AUTEUR']}
        #            admin: {password: adminpass, roles:['ROLE_ADMIN']}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main #--définit dans providers
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /platform
            logout:
                path: fos_user_security_logout
                target: /platform
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml    
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
